"""phase 2 schema

Revision ID: 0b876a2c1921
Revises:
Create Date: 2026-08-11 14:10:53.136880
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Frozen to the tables this revision actually creates. Do not import live
# APP_TABLES — later models would make a fresh `alembic upgrade head` fail.

revision: str = "0b876a2c1921"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profiles",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column(
            "locale", sa.String(), server_default=sa.text("'fa'"), nullable=False
        ),
        sa.Column(
            "credit_balance_cached",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "free_campaigns_remaining",
            sa.Integer(),
            server_default=sa.text("1"),
            nullable=False,
        ),
        sa.Column(
            "sample_seeded",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "anonymous_sessions",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("token_hash", sa.String(), nullable=False),
        sa.Column("claimed_by_user_id", sa.UUID(), nullable=True),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["claimed_by_user_id"], ["profiles.user_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_anonymous_sessions_token_hash"),
        "anonymous_sessions",
        ["token_hash"],
        unique=True,
    )
    op.create_table(
        "brands",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("instagram_handle", sa.String(), nullable=True),
        sa.Column("website", sa.String(), nullable=True),
        sa.Column("target_audience", sa.String(), nullable=True),
        sa.Column("tone", sa.String(), nullable=True),
        sa.Column("visual_style", sa.String(), nullable=True),
        sa.Column("primary_color", sa.String(), nullable=True),
        sa.Column("secondary_color", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "visual_style is null or visual_style in ('luxury', 'minimal', 'friendly', 'bold', 'persian_traditional', 'modern')",
            name="ck_brands_visual_style",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["profiles.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_brands_user_id"), "brands", ["user_id"], unique=False)
    op.create_table(
        "brand_assets",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("brand_id", sa.UUID(), nullable=False),
        sa.Column("asset_type", sa.String(), nullable=False),
        sa.Column("storage_path", sa.String(), nullable=False),
        sa.Column(
            "metadata_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "asset_type in ('logo', 'reference_image', 'product_reference')",
            name="ck_brand_assets_asset_type",
        ),
        sa.ForeignKeyConstraint(["brand_id"], ["brands.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_brand_assets_brand_id"), "brand_assets", ["brand_id"], unique=False
    )
    op.create_table(
        "products",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("brand_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(), server_default=sa.text("''"), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("price_text", sa.String(), nullable=True),
        sa.Column("main_benefit", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["brand_id"], ["brands.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["profiles.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_products_brand_id"), "products", ["brand_id"], unique=False
    )
    op.create_index(op.f("ix_products_user_id"), "products", ["user_id"], unique=False)
    op.create_table(
        "campaigns",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("anonymous_session_id", sa.UUID(), nullable=True),
        sa.Column("brand_id", sa.UUID(), nullable=True),
        sa.Column("product_id", sa.UUID(), nullable=True),
        sa.Column("objective", sa.String(), nullable=True),
        sa.Column("audience", sa.String(), nullable=True),
        sa.Column("visual_style", sa.String(), nullable=True),
        sa.Column("selected_concept_id", sa.UUID(), nullable=True),
        sa.Column(
            "status", sa.String(), server_default=sa.text("'draft'"), nullable=False
        ),
        sa.Column(
            "is_free_campaign",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column("concept_round", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "objective is null or objective in ('sell_product', 'new_product', 'promotion', 'brand_awareness')",
            name="ck_campaigns_objective",
        ),
        sa.CheckConstraint(
            "status in ('draft', 'brief_complete', 'concepts_ready', 'concept_selected', 'queued', 'generating', 'ready', 'partial_failed', 'failed')",
            name="ck_campaigns_status",
        ),
        sa.CheckConstraint(
            "visual_style is null or visual_style in ('luxury', 'minimal', 'friendly', 'bold', 'persian_traditional', 'modern')",
            name="ck_campaigns_visual_style",
        ),
        sa.CheckConstraint(
            "user_id is not null or anonymous_session_id is not null",
            name="ck_campaigns_has_owner",
        ),
        sa.ForeignKeyConstraint(
            ["anonymous_session_id"], ["anonymous_sessions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["brand_id"], ["brands.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["profiles.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_campaigns_anonymous_session_id"),
        "campaigns",
        ["anonymous_session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_campaigns_brand_id"), "campaigns", ["brand_id"], unique=False
    )
    op.create_index(
        op.f("ix_campaigns_product_id"), "campaigns", ["product_id"], unique=False
    )
    op.create_index(
        "ix_campaigns_user_created",
        "campaigns",
        ["user_id", sa.literal_column("created_at desc")],
        unique=False,
    )
    op.create_index(
        op.f("ix_campaigns_user_id"), "campaigns", ["user_id"], unique=False
    )
    op.create_table(
        "product_images",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("storage_path", sa.String(), nullable=False),
        sa.Column(
            "is_primary", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_product_images_product_id"),
        "product_images",
        ["product_id"],
        unique=False,
    )
    op.create_table(
        "campaign_assets",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.Column("asset_type", sa.String(), nullable=False),
        sa.Column("storage_path", sa.String(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("template_id", sa.String(), nullable=True),
        sa.Column(
            "metadata_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "asset_type in ('uploaded_product', 'product_cutout', 'generated_background', 'feed_final', 'story_final', 'carousel_1', 'carousel_2', 'carousel_3')",
            name="ck_campaign_assets_asset_type",
        ),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_campaign_assets_campaign_id"),
        "campaign_assets",
        ["campaign_id"],
        unique=False,
    )
    op.create_table(
        "campaign_concepts",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.Column("concept_number", sa.Integer(), nullable=False),
        sa.Column("title_fa", sa.String(), nullable=False),
        sa.Column("headline_fa", sa.String(), nullable=False),
        sa.Column("description_fa", sa.String(), nullable=False),
        sa.Column("visual_direction", sa.String(), nullable=False),
        sa.Column("background_prompt", sa.String(), nullable=False),
        sa.Column(
            "raw_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "selected", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_campaign_concepts_campaign_id"),
        "campaign_concepts",
        ["campaign_id"],
        unique=False,
    )
    op.create_table(
        "campaign_copy",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.Column("copy_type", sa.String(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column(
            "metadata_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "copy_type in ('caption_short', 'caption_friendly', 'caption_persuasive', 'story', 'cta', 'hashtags', 'reel_concept')",
            name="ck_campaign_copy_copy_type",
        ),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_campaign_copy_campaign_id"),
        "campaign_copy",
        ["campaign_id"],
        unique=False,
    )
    op.create_table(
        "generation_jobs",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("job_type", sa.String(), nullable=False),
        sa.Column("provider", sa.String(), nullable=True),
        sa.Column("model", sa.String(), nullable=True),
        sa.Column("provider_job_id", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "input_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "output_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "job_type in ('campaign_generation')", name="ck_generation_jobs_job_type"
        ),
        sa.CheckConstraint(
            "status in ('queued', 'processing', 'succeeded', 'failed', 'cancelled')",
            name="ck_generation_jobs_status",
        ),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["profiles.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_generation_jobs_campaign_id"),
        "generation_jobs",
        ["campaign_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_generation_jobs_user_id"), "generation_jobs", ["user_id"], unique=False
    )
    op.create_index(
        "uq_generation_jobs_active",
        "generation_jobs",
        ["campaign_id"],
        unique=True,
        postgresql_where=sa.text("status in ('queued', 'processing')"),
    )
    # ### end Alembic commands ###
    _enable_deny_all_rls()


def _enable_deny_all_rls() -> None:
    """
    Row Level Security on, with no grants for the browser-facing roles.

    Defence in depth for the Data API: if the publishable key ever leaks,
    PostgREST's `anon` and `authenticated` roles reach nothing. It is not the
    authorization mechanism — FastAPI verifies ownership on every request
    (spec §27).

    No policies are created here, which locks out afarin_app too. Revision
    9f2b7c4d5e10 adds the policy that lets the backend in; the two are kept
    apart so the fix reads as the deliberate correction it is.
    """
    phase_2_tables = (
        "profiles",
        "anonymous_sessions",
        "brands",
        "brand_assets",
        "products",
        "product_images",
        "campaigns",
        "campaign_concepts",
        "campaign_copy",
        "campaign_assets",
        "generation_jobs",
    )
    for table in phase_2_tables:
        op.execute(f"alter table {table} enable row level security")
        op.execute(f"revoke all on table {table} from anon, authenticated")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_generation_jobs_active",
        table_name="generation_jobs",
        postgresql_where=sa.text("status in ('queued', 'processing')"),
    )
    op.drop_index(op.f("ix_generation_jobs_user_id"), table_name="generation_jobs")
    op.drop_index(op.f("ix_generation_jobs_campaign_id"), table_name="generation_jobs")
    op.drop_table("generation_jobs")
    op.drop_index(op.f("ix_campaign_copy_campaign_id"), table_name="campaign_copy")
    op.drop_table("campaign_copy")
    op.drop_index(
        op.f("ix_campaign_concepts_campaign_id"), table_name="campaign_concepts"
    )
    op.drop_table("campaign_concepts")
    op.drop_index(op.f("ix_campaign_assets_campaign_id"), table_name="campaign_assets")
    op.drop_table("campaign_assets")
    op.drop_index(op.f("ix_product_images_product_id"), table_name="product_images")
    op.drop_table("product_images")
    op.drop_index(op.f("ix_campaigns_user_id"), table_name="campaigns")
    op.drop_index("ix_campaigns_user_created", table_name="campaigns")
    op.drop_index(op.f("ix_campaigns_product_id"), table_name="campaigns")
    op.drop_index(op.f("ix_campaigns_brand_id"), table_name="campaigns")
    op.drop_index(op.f("ix_campaigns_anonymous_session_id"), table_name="campaigns")
    op.drop_table("campaigns")
    op.drop_index(op.f("ix_products_user_id"), table_name="products")
    op.drop_index(op.f("ix_products_brand_id"), table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_brand_assets_brand_id"), table_name="brand_assets")
    op.drop_table("brand_assets")
    op.drop_index(op.f("ix_brands_user_id"), table_name="brands")
    op.drop_table("brands")
    op.drop_index(
        op.f("ix_anonymous_sessions_token_hash"), table_name="anonymous_sessions"
    )
    op.drop_table("anonymous_sessions")
    op.drop_table("profiles")
    # ### end Alembic commands ###
