"""
Persian campaign copy fixtures.

A faithful port of frontend/lib/api/mock/fixtures/copy.ts, including the
whitespace and emoji, so that a campaign generated by the backend reads exactly
like one generated by the Phase 1 mock.
"""

import re
from dataclasses import dataclass

from app.content.context import CopyContext, pick, rotate

CTAS: dict[str, tuple[str, ...]] = {
    "sell_product": ("همین حالا سفارش بده", "برای خرید دایرکت بده", "سفارشت رو ثبت کن"),
    "new_product": ("اولین نفر باش", "همین حالا ببینش", "نظرت رو برامون بنویس"),
    "promotion": (
        "تا تموم نشده سفارش بده",
        "از این قیمت جا نمون",
        "همین امروز استفاده کن",
    ),
    "brand_awareness": ("ما رو دنبال کن", "با ما همراه شو", "صفحه‌مون رو ببین"),
}


def build_ctas(ctx: CopyContext) -> list[str]:
    return rotate(CTAS[ctx.objective], ctx.round)


def build_primary_cta(ctx: CopyContext) -> str:
    return build_ctas(ctx)[0]


def _price_line(ctx: CopyContext) -> str | None:
    if not ctx.price_text:
        return None
    if ctx.objective == "promotion":
        return f"💰 {ctx.price_text} — فرصت محدود"
    return f"💰 {ctx.price_text}"


def _brand_signature(ctx: CopyContext) -> str | None:
    return f"— {ctx.brand_name}" if ctx.brand_name else None


def _join_lines(lines: list[str | None]) -> str:
    return "\n".join(line for line in lines if line)


@dataclass(frozen=True, slots=True)
class CaptionSet:
    caption_short: str
    caption_friendly: str
    caption_persuasive: str


def build_captions(ctx: CopyContext) -> CaptionSet:
    """Spec §16 section 4 — three captions with distinct tones."""
    cta = build_primary_cta(ctx)
    benefit = ctx.benefit or ctx.description or "کیفیتی که فرقش رو حس می‌کنی"
    audience = f"مناسب {ctx.audience}" if ctx.audience else None

    short_variants = [
        _join_lines(
            [
                f"{ctx.product_name} ✨",
                benefit,
                _price_line(ctx),
                f"{cta} 👇",
                _brand_signature(ctx),
            ]
        ),
        _join_lines(
            [
                f"{ctx.product_name} رسید ✨",
                _price_line(ctx),
                cta,
                _brand_signature(ctx),
            ]
        ),
    ]

    friendly_variants = [
        _join_lines(
            [
                "سلام رفقا 👋",
                (
                    f"این {ctx.product_name} یکی از اون چیزهاییه که وقتی امتحانش می‌کنی "
                    "می‌گی چرا زودتر نخریدم!"
                ),
                f"{benefit} 🙌" if benefit else None,
                audience,
                _price_line(ctx),
                "اگه سوالی داشتی راحت دایرکت بده، جواب می‌دیم 💬",
                cta,
            ]
        ),
        _join_lines(
            [
                "یه پیشنهاد خودمونی 🤍",
                f"{ctx.product_name} رو مخصوص کسایی آوردیم که سختگیرن.",
                benefit,
                _price_line(ctx),
                "کامنت بذار تا راهنماییت کنیم 💬",
                cta,
            ]
        ),
    ]

    persuasive_variants = [
        _join_lines(
            [
                f"چرا {ctx.product_name}؟",
                f"چون {benefit}.",
                f"{audience} — دقیقاً همون چیزی که دنبالشی." if audience else None,
                _price_line(ctx),
                "تعداد محدوده و ممکنه زود تموم بشه ⏳",
                f"{cta} 👇",
                _brand_signature(ctx),
            ]
        ),
        _join_lines(
            [
                f"فرق {ctx.product_name} با بقیه چیه؟",
                f"{benefit} — همین.",
                _price_line(ctx),
                "اگه دنبال یه انتخاب مطمئنی، این همونه.",
                f"{cta} ✅",
                _brand_signature(ctx),
            ]
        ),
    ]

    return CaptionSet(
        caption_short=pick(short_variants, ctx.round),
        caption_friendly=pick(friendly_variants, ctx.round),
        caption_persuasive=pick(persuasive_variants, ctx.round),
    )


def build_story_ideas(ctx: CopyContext) -> list[str]:
    """Spec §16 section 5 — three short Story texts."""
    cta = build_primary_cta(ctx)
    price_prefix = f"{ctx.price_text} 💰\n" if ctx.price_text else ""
    variants = [
        [
            f"{ctx.product_name} موجود شد ✨\nسوایپ کن و ببین",
            "کدوم رو بیشتر دوست داری؟ 🤔\nتوی نظرسنجی رأی بده",
            f"{price_prefix}{cta} 👆",
        ],
        [
            f"یه سؤال 👀\nدنبال {ctx.product_name} خوب بودی؟",
            "پشت‌صحنه آماده‌سازی سفارش‌ها 📦\nهر سفارش با دقت بسته‌بندی می‌شه",
            f"آخرین فرصت ⏳\n{cta}",
        ],
    ]
    return pick(variants, ctx.round)


def build_hashtags(ctx: CopyContext) -> str:
    base = [
        "#خرید_آنلاین",
        "#فروشگاه_اینترنتی",
        "#ارسال_به_سراسر_کشور",
        "#کیفیت_تضمینی",
    ]
    by_objective = {
        "sell_product": ["#خرید_مطمئن", "#پیشنهاد_ویژه"],
        "new_product": ["#تازه_رسید", "#محصول_جدید"],
        "promotion": ["#تخفیف", "#فروش_ویژه", "#حراج"],
        "brand_awareness": ["#برند_ایرانی", "#کار_ایرانی"],
    }
    brand_tag: list[str] = []
    if ctx.brand_name:
        slug = re.sub(r"\s+", "_", ctx.brand_name.strip())
        brand_tag.append(f"#{slug}")

    return " ".join(
        rotate([*base, *by_objective[ctx.objective], *brand_tag], ctx.round)
    )


@dataclass(frozen=True, slots=True)
class ReelConcept:
    hook_fa: str
    scenes_fa: list[str]
    cta_fa: str
    voiceover_fa: str
    duration_seconds: int

    def to_dict(self) -> dict:
        return {
            "hook_fa": self.hook_fa,
            "scenes_fa": self.scenes_fa,
            "cta_fa": self.cta_fa,
            "voiceover_fa": self.voiceover_fa,
            "duration_seconds": self.duration_seconds,
        }


def build_reel_concept(ctx: CopyContext) -> ReelConcept:
    """Spec §16 section 6 — storyboard only. No video is generated, in any phase."""
    cta = build_primary_cta(ctx)
    benefit = ctx.benefit or "کیفیتی که حس می‌شه"
    price_suffix = f" و قیمت {ctx.price_text}" if ctx.price_text else ""

    variants = [
        ReelConcept(
            hook_fa=f"اگه دنبال {ctx.product_name} خوب می‌گردی، سه ثانیه وقت بده",
            scenes_fa=[
                "نمای نزدیک از محصول در حال باز شدن بسته‌بندی، نور گرم",
                f"نمای متوسط از استفاده واقعی از محصول، متن روی تصویر: «{benefit}»",
                f"نمای پایانی از محصول کنار لوگو{price_suffix}",
            ],
            cta_fa=cta,
            voiceover_fa=f"{ctx.product_name}؛ {benefit}. {cta}.",
            duration_seconds=12,
        ),
        ReelConcept(
            hook_fa=f"این اشتباه رو موقع خرید {ctx.product_name} نکن!",
            scenes_fa=[
                "نمای سریع از یک انتخاب اشتباه و بی‌کیفیت",
                f"کات به محصول ما، نمای چرخشی آهسته، متن: «{benefit}»",
                "نمای پایانی: بسته‌بندی آماده ارسال با لوگوی برند",
            ],
            cta_fa=cta,
            voiceover_fa=f"فرقش اینجاست: {benefit}. {cta}.",
            duration_seconds=14,
        ),
    ]

    return pick(variants, ctx.round)
